Exception on /api/V0.1/trip/advice/park [PUT]
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "adviceapi.py", line 112, in put
    return AdviceMe(request)
  File "adviceapi.py", line 47, in AdviceMe
    advice ["timestamp"] = json.dump(datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S'))
TypeError: dump() missing 1 required positional argument: 'fp'
Exception on /api/V0.1/trip/advice/charge [PUT]
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "adviceapi.py", line 133, in put
    return AdviceMe(request)
  File "adviceapi.py", line 47, in AdviceMe
    advice ["timestamp"] = json.dump(datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S'))
TypeError: dump() missing 1 required positional argument: 'fp'
Illegal request b'{"type": 1}'
Exception on /api/V0.2/trip/start [PUT]
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "adviceapi.py", line 78, in put
    return AdviceMe(request)
  File "adviceapi.py", line 55, in AdviceMe
    advice ["timestamp"] = json.dump(datetime.datetime.now(), default=date_handler)
TypeError: dump() missing 1 required positional argument: 'fp'
Exception on /api/V0.1/trip/advice/speed [PUT]
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "adviceapi.py", line 99, in put
    return AdviceMe(request)
  File "adviceapi.py", line 55, in AdviceMe
    advice ["timestamp"] = json.dump(datetime.datetime.now(), default=date_handler)
TypeError: dump() missing 1 required positional argument: 'fp'
Exception on /api/V0.1/trip/advice/park [PUT]
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "adviceapi.py", line 120, in put
    return AdviceMe(request)
  File "adviceapi.py", line 55, in AdviceMe
    advice ["timestamp"] = json.dump(datetime.datetime.now(), default=date_handler)
TypeError: dump() missing 1 required positional argument: 'fp'
Exception on /api/V0.1/trip/advice/charge [PUT]
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "adviceapi.py", line 141, in put
    return AdviceMe(request)
  File "adviceapi.py", line 55, in AdviceMe
    advice ["timestamp"] = json.dump(datetime.datetime.now(), default=date_handler)
TypeError: dump() missing 1 required positional argument: 'fp'
Illegal request b'{"type": 1}'
Illegal request b'{"type": 1}'
Exception on /api/V0.2/trip/start [PUT]
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\Program Files\Anaconda3\lib\json\__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\Anaconda3\lib\json\encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Anaconda3\lib\json\encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\Anaconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 6, 22, 11, 16, 1, 258514) is not JSON serializable
Exception on /api/V0.1/trip/advice/speed [PUT]
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask_restful\representations\json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "C:\Program Files\Anaconda3\lib\json\__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\Anaconda3\lib\json\encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Anaconda3\lib\json\encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\Anaconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 6, 22, 11, 16, 2, 416056) is not JSON serializable
